version: '3'
services:
  redis:
    image: 'bitnami/redis:7.0.4'
    networks:
      - network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

networks:
  network:
    driver: bridge
