version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
